[project]
name = "microblog"
version = "0.1.0"
description = "Microblog: training flask project, based on Miguel Grinberg's course"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flask>=3.1.2",
]

[dependency-groups]
dev = [
    "ruff>=0.14.2",
]
